name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.3.0'
          registry-url: https://registry.npmjs.org/

      - name: Yarn
        run: yarn install

      - name: Publish 🚀
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  docs:
    name: Docs
    runs-on: ubuntu-latest
    needs: [publish]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.3.0'

      - name: Yarn
        run: cd docs && yarn install && yarn build && cd ../

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: docs
          FOLDER: docs/dist
          CLEAN: true